"""Generate ios/shared/.../R.kt from the Android app's res/values/strings.xml.

The ported Compose code calls stringResource(R.string.x); on iOS R.string.x is
the English text itself and stringResource formats it (see compat/Resources.kt).
Re-run after pulling upstream string changes:
    python ios/tools/gen_strings.py
"""
import os
import re
import xml.etree.ElementTree as ET

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SRC = os.path.join(ROOT, "app", "src", "main", "res", "values", "strings.xml")
OUT = os.path.join(ROOT, "ios", "shared", "src", "commonMain", "kotlin", "com", "music", "bitchord", "R.kt")

BS = chr(92)  # backslash, spelled out so no tool along the way can eat it


def text_of(el):
    # Inner XML (keeps <b> etc. as text), then Android's resource unescaping.
    raw = (el.text or "") + "".join(ET.tostring(c, encoding="unicode") for c in el)
    raw = raw.strip()
    if len(raw) >= 2 and raw[0] == '"' and raw[-1] == '"':
        raw = raw[1:-1]
    for escaped, plain in ((BS + "'", "'"), (BS + '"', '"'), (BS + "n", chr(10)), (BS + "t", chr(9)),
                           (BS + "@", "@"), (BS + "?", "?")):
        raw = raw.replace(escaped, plain)
    return raw


def kt(s):
    out = s.replace(BS, BS + BS).replace('"', BS + '"').replace(chr(10), BS + "n").replace("$", BS + "$")
    return '"' + out + '"'


tree = ET.parse(SRC)
strings, arrays, plurals = [], [], []
for el in tree.getroot():
    name = el.get("name")
    if not name:
        continue
    ident = re.sub(r"[^A-Za-z0-9_]", "_", name)
    if el.tag == "string":
        strings.append((ident, text_of(el)))
    elif el.tag == "string-array":
        arrays.append((ident, [text_of(i) for i in el.findall("item")]))
    elif el.tag == "plurals":
        items = {i.get("quantity"): text_of(i) for i in el.findall("item")}
        plurals.append((ident, items.get("one", items.get("other", "")), items.get("other", "")))

lines = [
    "// GENERATED by ios/tools/gen_strings.py from app/src/main/res/values/strings.xml - do not edit.",
    '@file:Suppress("ClassName", "ObjectPropertyName", "SpellCheckingInspection")',
    "",
    "package com.music.bitchord",
    "",
    "import com.music.bitchord.compat.PluralRes",
    "",
    "object R {",
    "    object string {",
]
for ident, value in strings:
    lines.append(f"        const val {ident}: String = {kt(value)}")
lines += ["    }", "", "    object array {"]
for ident, items in arrays:
    lines.append(f"        val {ident}: List<String> = listOf({', '.join(kt(i) for i in items)})")
lines += ["    }", "", "    object plurals {"]
for ident, one, other in plurals:
    lines.append(f"        val {ident}: PluralRes = PluralRes({kt(one)}, {kt(other)})")
lines += ["    }", "}", ""]

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write("\n".join(lines))
print(f"{len(strings)} strings, {len(arrays)} arrays, {len(plurals)} plurals -> {OUT}")
